DROP TABLE M_GREETING;
DROP TABLE M_TOP_PHOTO;
DROP TABLE M_GALLERY_PHOTO;
DROP TABLE M_PRESENTER_PROFILE;
DROP TABLE M_PARTICIPANT_PROFILE;
DROP TABLE M_NEKO;
DROP TABLE M_IE;

CREATE DATABASE shiori_db;
USE shiori_db;


CREATE TABLE M_IE (
	id VARCHAR(5) PRIMARY KEY,
	name VARCHAR(20) NOT NULL
);

CREATE TABLE M_GREETING (
	id VARCHAR(5) PRIMARY KEY,
	display_number INT NOT NULL, 
	content VARCHAR(4096) NOT NULL,
	delete_flag TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE M_TOP_PHOTO (
	id VARCHAR(5) PRIMARY KEY,
	s3_object_name VARCHAR(2048) NOT NULL,
	delete_flag TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE M_GALLERY_PHOTO (
	id VARCHAR(5) PRIMARY KEY,
	s3_object_name VARCHAR(2048) NOT NULL,
	display_number int NOT NULL,
	delete_flag TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE M_PRESENTER_PROFILE (
	kaede_flg TINYINT PRIMARY KEY,
	ie_id VARCHAR(5) NOT NULL,
	photo_s3_object_name VARCHAR(2048),
	last_name VARCHAR(20) NOT NULL,
	first_name VARCHAR(20) NOT NULL,
	last_name_kana VARCHAR(20) NOT NULL,
	first_name_kana VARCHAR(20) NOT NULL,
	birth_date DATE NOT NULL,
	birth_place VARCHAR(100) NOT NULL,
	job VARCHAR(100) NOT NULL,
	hobby VARCHAR(100) NOT NULL,
	ramen VARCHAR(100) NOT NULL,
	nickname VARCHAR(20) NOT NULL,
	like_by VARCHAR(100) NOT NULL,
	FOREIGN KEY (ie_id) REFERENCES M_IE(id)
);

CREATE TABLE M_PARTICIPANT_PROFILE (
	id VARCHAR(5) PRIMARY KEY,
	ie_id VARCHAR(5) NOT NULL,
	display_number INT NOT NULL,
	photo_s3_object_name VARCHAR(2048),
	last_name VARCHAR(20) NOT NULL,
	first_name VARCHAR(20) NOT NULL,
	last_name_kana VARCHAR(20) NOT NULL,
	first_name_kana VARCHAR(20) NOT NULL,
	birth_date DATE NOT NULL,
	birth_place VARCHAR(100) NOT NULL,
	job VARCHAR(100) NOT NULL,
	hobby VARCHAR(100) NOT NULL,
	relation VARCHAR(100) NOT NULL,
	like_food VARCHAR(100) NOT NULL,
	message VARCHAR(100) NOT NULL,
	FOREIGN KEY (ie_id) REFERENCES M_IE(id)
);

CREATE TABLE M_NEKO (
	id VARCHAR(5) PRIMARY KEY,
	ie_id VARCHAR(5) NOT NULL,
	display_number int NOT NULL,
	photo_s3_object_name VARCHAR(2048),
	name VARCHAR(20) NOT NULL,
	age INT NOT NULL,
	temperament VARCHAR(100) NOT NULL,
	like_food VARCHAR(100) NOT NULL,
	FOREIGN KEY (ie_id) REFERENCES M_IE(id)
);
