// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "yagi"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "トップ画像と挨拶文を取得。挨拶文は念のため配列だが、要素は１つしか返さない想定。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "top"
                ],
                "summary": "トップページ取得",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resource.TopPageResource"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/access": {
            "get": {
                "description": "アクセス情報を返却。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "access"
                ],
                "summary": "アクセスページ取得",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resource.AccessPageResource"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/families": {
            "get": {
                "description": "主催者・参加者・猫プロフィール情報を取得",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "families"
                ],
                "summary": "家族情報取得",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resource.FamiliesPageResource"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/gallery": {
            "get": {
                "description": "ギャラリー画像の一覧をlimitとoffsetで取得",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gallery"
                ],
                "summary": "ギャラリー画像取得",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "取得件数",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "開始位置",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resource.GalleryPhotoPageResource"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "resource.AccessPageResource": {
            "type": "object",
            "properties": {
                "gatheringDate": {
                    "type": "string",
                    "example": "2000-01-31T00:00:00+09:00"
                },
                "gatheringSpot": {
                    "type": "string",
                    "example": "松戸新田駅の近くのいなげや"
                },
                "latitude": {
                    "type": "string",
                    "example": "40.999999"
                },
                "longitude": {
                    "type": "string",
                    "example": "140.999999"
                },
                "restaurantName": {
                    "type": "string",
                    "example": "oisiiRestaurant"
                },
                "restaurantUrl": {
                    "type": "string",
                    "example": "https://oisiiRestaurant.com"
                },
                "startingDate": {
                    "type": "string",
                    "example": "2000-01-31T00:15:00+09:00"
                },
                "venueAccessPageUrl": {
                    "type": "string",
                    "example": "https://kaijou/access"
                },
                "venueAddress": {
                    "type": "string",
                    "example": "千葉県松戸市上本郷1-2-999"
                }
            }
        },
        "resource.FamiliesPageResource": {
            "type": "object",
            "properties": {
                "families": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/resource.FamilyResource"
                    }
                }
            }
        },
        "resource.FamilyResource": {
            "type": "object",
            "properties": {
                "ieId": {
                    "type": "string",
                    "example": "IE000"
                },
                "ieName": {
                    "type": "string",
                    "example": "田中"
                },
                "nekoProfiles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/resource.NekoProfileResource"
                    }
                },
                "participantProfiles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/resource.ParticipantProfileResource"
                    }
                },
                "presenterProfile": {
                    "$ref": "#/definitions/resource.PresenterProfileResource"
                }
            }
        },
        "resource.GalleryPhotoPageResource": {
            "type": "object",
            "properties": {
                "galleryPhotos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/resource.GalleryPhotoResource"
                    }
                }
            }
        },
        "resource.GalleryPhotoResource": {
            "type": "object",
            "properties": {
                "displayNumber": {
                    "type": "string",
                    "example": "2"
                },
                "id": {
                    "type": "string",
                    "example": "GP001"
                },
                "photoUrl": {
                    "type": "string",
                    "example": "https://s3url"
                }
            }
        },
        "resource.GreetingResource": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string",
                    "example": "こんにちは。たなかです。お忙しい中と存じますが云々。"
                }
            }
        },
        "resource.NekoProfileResource": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer",
                    "example": 30
                },
                "displayNumber": {
                    "type": "integer",
                    "example": 1
                },
                "id": {
                    "type": "string",
                    "example": "NK001"
                },
                "likeFood": {
                    "type": "string",
                    "example": "アーリオ・オーリオ・ペペロンティーノ"
                },
                "name": {
                    "type": "string",
                    "example": "nekoyagi"
                },
                "photoUrl": {
                    "type": "string",
                    "example": "https://nekoneko"
                },
                "temperament": {
                    "type": "string",
                    "example": "それとなくきつい性格"
                }
            }
        },
        "resource.ParticipantProfileResource": {
            "type": "object",
            "properties": {
                "birthDate": {
                    "type": "string",
                    "example": "1990-05-22"
                },
                "birthPlace": {
                    "type": "string",
                    "example": "北海道"
                },
                "displayNumber": {
                    "type": "integer",
                    "example": 2
                },
                "firstName": {
                    "type": "string",
                    "example": "田中"
                },
                "firstNameKana": {
                    "type": "string",
                    "example": "たなか"
                },
                "hobby": {
                    "type": "string",
                    "example": "youtube"
                },
                "id": {
                    "type": "string",
                    "example": "PP001"
                },
                "job": {
                    "type": "string",
                    "example": "ユーチューバー"
                },
                "lastName": {
                    "type": "string",
                    "example": "太郎"
                },
                "lastNameKana": {
                    "type": "string",
                    "example": "たろう"
                },
                "likeFood": {
                    "type": "string",
                    "example": "りんご"
                },
                "message": {
                    "type": "string",
                    "example": "よろしく！"
                },
                "photoUrl": {
                    "type": "string",
                    "example": "https://tanakapapagazou"
                },
                "relation": {
                    "type": "string",
                    "example": "父"
                }
            }
        },
        "resource.PresenterProfileResource": {
            "type": "object",
            "properties": {
                "birthDate": {
                    "type": "string",
                    "example": "1999-01-22"
                },
                "birthPlace": {
                    "type": "string",
                    "example": "沖縄"
                },
                "firstName": {
                    "type": "string",
                    "example": "田中"
                },
                "firstNameKana": {
                    "type": "string",
                    "example": "たなか"
                },
                "hobby": {
                    "type": "string",
                    "example": "どろけい"
                },
                "job": {
                    "type": "string",
                    "example": "警官"
                },
                "lastName": {
                    "type": "string",
                    "example": "太郎"
                },
                "lastNameKana": {
                    "type": "string",
                    "example": "たろう"
                },
                "likeBy": {
                    "type": "string",
                    "example": "全て"
                },
                "nickName": {
                    "type": "string",
                    "example": "たろちゃん"
                },
                "photoUrl": {
                    "type": "string",
                    "example": "https://tarouphoto"
                },
                "ramen": {
                    "type": "string",
                    "example": "あぶとら"
                }
            }
        },
        "resource.TopPageResource": {
            "type": "object",
            "properties": {
                "greeting": {
                    "$ref": "#/definitions/resource.GreetingResource"
                },
                "topPhoto": {
                    "$ref": "#/definitions/resource.TopPhotoResource"
                }
            }
        },
        "resource.TopPhotoResource": {
            "type": "object",
            "properties": {
                "photoUrl": {
                    "type": "string",
                    "example": "https://suzukinogazou"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Shiori API",
	Description:      "顔合わせアプリのエンドポイントを提供",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
