basePath: /
definitions:
  resource.AccessPageResource:
    properties:
      gatheringDate:
        description: GatheringDate      util.JSTTime `json:"gatheringDate" example:"2000-01-31T00:00:00+09:00"`
        example: "2000-01-31T00:00:00+09:00"
        type: string
      gatheringSpot:
        example: 松戸新田駅の近くのいなげや
        type: string
      latitude:
        example: "40.999999"
        type: string
      longitude:
        example: "140.999999"
        type: string
      restaurantName:
        example: oisiiRestaurant
        type: string
      restaurantUrl:
        example: https://oisiiRestaurant.com
        type: string
      startingDate:
        description: StartingDate       util.JSTTime `json:"startingDate" example:"2000-01-31T00:15:00+09:00"`
        example: "2000-01-31T00:15:00+09:00"
        type: string
      venueAccessPageUrl:
        example: https://kaijou/access
        type: string
      venueAddress:
        example: 千葉県松戸市上本郷1-2-999
        type: string
    type: object
  resource.FamiliesPageResource:
    properties:
      families:
        items:
          $ref: '#/definitions/resource.FamilyResource'
        type: array
    type: object
  resource.FamilyResource:
    properties:
      ieId:
        example: IE000
        type: string
      ieName:
        example: 田中
        type: string
      nekoProfiles:
        items:
          $ref: '#/definitions/resource.NekoProfileResource'
        type: array
      participantProfiles:
        items:
          $ref: '#/definitions/resource.ParticipantProfileResource'
        type: array
      presenterProfile:
        $ref: '#/definitions/resource.PresenterProfileResource'
    type: object
  resource.GalleryPhotoPageResource:
    properties:
      galleryPhotos:
        items:
          $ref: '#/definitions/resource.GalleryPhotoResource'
        type: array
    type: object
  resource.GalleryPhotoResource:
    properties:
      displayNumber:
        example: "2"
        type: string
      id:
        example: GP001
        type: string
      photoUrl:
        example: https://s3url
        type: string
    type: object
  resource.GreetingResource:
    properties:
      content:
        example: こんにちは。たなかです。お忙しい中と存じますが云々。
        type: string
    type: object
  resource.NekoProfileResource:
    properties:
      age:
        example: 30
        type: integer
      displayNumber:
        example: 1
        type: integer
      id:
        example: NK001
        type: string
      likeFood:
        example: アーリオ・オーリオ・ペペロンティーノ
        type: string
      name:
        example: nekoyagi
        type: string
      photoUrl:
        example: https://nekoneko
        type: string
      temperament:
        example: それとなくきつい性格
        type: string
    type: object
  resource.ParticipantProfileResource:
    properties:
      birthDate:
        example: "1990-05-22"
        type: string
      birthPlace:
        example: 北海道
        type: string
      displayNumber:
        example: 2
        type: integer
      firstName:
        example: 田中
        type: string
      firstNameKana:
        example: たなか
        type: string
      hobby:
        example: youtube
        type: string
      id:
        example: PP001
        type: string
      job:
        example: ユーチューバー
        type: string
      lastName:
        example: 太郎
        type: string
      lastNameKana:
        example: たろう
        type: string
      likeFood:
        example: りんご
        type: string
      message:
        example: よろしく！
        type: string
      photoUrl:
        example: https://tanakapapagazou
        type: string
      relation:
        example: 父
        type: string
    type: object
  resource.PresenterProfileResource:
    properties:
      birthDate:
        example: "1999-01-22"
        type: string
      birthPlace:
        example: 沖縄
        type: string
      firstName:
        example: 田中
        type: string
      firstNameKana:
        example: たなか
        type: string
      hobby:
        example: どろけい
        type: string
      job:
        example: 警官
        type: string
      lastName:
        example: 太郎
        type: string
      lastNameKana:
        example: たろう
        type: string
      likeBy:
        example: 全て
        type: string
      nickName:
        example: たろちゃん
        type: string
      photoUrl:
        example: https://tarouphoto
        type: string
      ramen:
        example: あぶとら
        type: string
    type: object
  resource.TopPageResource:
    properties:
      greeting:
        $ref: '#/definitions/resource.GreetingResource'
      topPhoto:
        $ref: '#/definitions/resource.TopPhotoResource'
    type: object
  resource.TopPhotoResource:
    properties:
      photoUrl:
        example: https://suzukinogazou
        type: string
    type: object
info:
  contact: {}
  description: 顔合わせアプリのエンドポイントを提供
  license:
    name: yagi
  title: Shiori API
  version: "1.0"
paths:
  /access:
    get:
      consumes:
      - application/json
      description: アクセス情報を返却。
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resource.AccessPageResource'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: アクセスページ取得
      tags:
      - access
  /families:
    get:
      consumes:
      - application/json
      description: 主催者・参加者・猫プロフィール情報を取得
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resource.FamiliesPageResource'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 家族情報取得
      tags:
      - families
  /gallery:
    get:
      consumes:
      - application/json
      description: ギャラリー画像の一覧をlimitとoffsetで取得
      parameters:
      - default: 20
        description: 取得件数
        in: query
        name: limit
        type: integer
      - default: 0
        description: 開始位置
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resource.GalleryPhotoPageResource'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: ギャラリー画像取得
      tags:
      - gallery
  /top:
    get:
      consumes:
      - application/json
      description: トップ画像と挨拶文を取得。
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resource.TopPageResource'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: トップページ取得
      tags:
      - top
swagger: "2.0"
